name: store
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


# ------------------------ packages --------------------------- #

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider:
  # Network
  http:
  # Loading
  flutter_spinkit:
  modal_progress_hud_nsn:
  shimmer:
  # Icons
  iconsax:
  cupertino_icons: ^1.0.6
  # local storage
  shared_preferences:
  # utils:
  intl:
  logger:
  url_launcher:
  connectivity:
  flutter_otp_text_field:
  step_progress_indicator: ^1.0.2
  smooth_page_indicator:
  fluttertoast: ^8.2.4
  image_picker: 
  file_picker:
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.2
  cached_network_image: ^3.3.1
  readmore: ^2.2.0
  flutter_floating_bottom_bar: ^1.2.0
  timeago: ^3.6.1
  flutter_quill: ^9.3.21
  chart_sparkline: ^1.0.15+1
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_credit_card: ^4.0.1
  firebase_core: ^2.24.2
  # fl: ^4.15.1
  # zego_uikit_signaling_plugin: ^2.7.15
  animated_toggle_switch: ^0.8.3
  flutter_datetime_picker_plus: ^2.2.0
  zego_uikit_prebuilt_call: ^4.15.4
  zego_uikit_signaling_plugin: ^2.8.2
  
# ------------------------ End-packages --------------------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


# ------------------------ Local Assets --------------------------- #


  assets:
    - assets/images/
    - assets/gif/
    - assets/images/auth/
    - assets/images/onBoard/
    - assets/naat/
    - assets/images/music/


# ------------------------ Local Fonts --------------------------- #

  fonts:
    - family: Varela
      fonts:
          - asset: assets/fonts/Varela-Regular.ttf
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
